import { Imobile } from "../models/mobile.interface";

export const mobileProducts:Array<Imobile>= [
    {
      id: 1,
      name: 'Apple iPhone 13 Pro(Graphite, 256GB )',
      brand: 'Apple',
      price: 120000,
      image: 'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
      isAvailable: true,
      rating : 4.9,
      specification:["6.2 inches","Exynos 2100","Triple rear (12MP+12MP+64MP), 10MP front","4000mAh","5G connectivity","120Hz refresh rate display","Wireless charging"]

    },
    {
      id: 2,
      name: 'Samsung Galaxy S21 (Phantom Black, 128GB ',
      brand: 'Samsung',
      price: 72000,
      image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg',
      isAvailable: false,
      rating : 4.5,
      specification: ["6.2 inches","Exynos 2100","Triple rear (12MP+12MP+64MP), 10MP from","4000mAh","5G connectivity","120Hz refresh rate display",
        "Wireless charging"]
    },
    {
      id: 3,
      name: 'Google Pixel 6 (Sorta Sunny, 128GB )',
      brand: 'Google',
      price: 58200,
      image: 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
      isAvailable: false,
      rating : 3.9,
      specification: ["6.4 inches",
      "Google Tensor",
     " Dual rear (50MP+12MP), 8MP front",
     " 4614mAh",
      "Google Assistant",
      "Tensor Processing Unit",
      "Night Sight photography"]
    },
    {
      id: 4,
      name: 'OnePlus 9 Pro(Morning Mist, 256GB )',
      brand: 'OnePlus',
      price: 67000,
      image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro-.jpg',
      isAvailable: true,
      rating : 2.9,
      specification:["6.7 inches",
        "Snapdragon  888",
        "Quad rear (48MP+50MP+8MP+2MP), 16MP front",
        "4500mAh",
        "Fluid AMOLED display",
        "Warp Charge 65T",
       " Dual stereo speakers"]
    },
    {
      id: 5,
      name: 'Xiaomi Mi 11 (Midnight Gray, 256GB )',
      brand: 'Xiaomi',
      price: 50000,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating : 4.8,
      specification: ["6.81 inches",
        "Snapdragon 888",
        "Triple rear (108MP+13MP+5MP), 20MP front",
       " 4600mAh",
        "120Hz refresh rate display",
        "Fast charging",
        "In-screen fingerprint sensor"]
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III   (Frosted Black, 256GB )',
      brand: 'Sony',
      price: 90000,
      image: 'https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-iii.jpg',
      isAvailable: true,
      rating : 2.5,
      specification:["6.5 inches","Snapdragon 888","Triple rear (12MP+12MP+12MP), 8MP front","4500mAh","4K OLED HDR display"," Cinematic recording","3D audio"]
    },
    {
      id: 7,
      name: 'LG Wing 5G   (Aurora Gray, 256GB )',
      brand: 'LG',
      price: 62000,
      image: '',
      isAvailable: false,
      rating : 1.5,
      specification:["6.8 inches",
        "Snapdragon 765G",
        "Triple rear (64MP+13MP+12MP), 32MP pop-up front",
        "4000mAh",
        "Swivel display",
       " Gimbal Motion Camera",
        "LG 3D Sound Engine"]
    },
    {
      id: 8,
      name: 'Huawei P40 Pro (Silver Frost, 256GB )',
      brand: 'Huawei',
      price: 62300,
      image: '',
      isAvailable: true,
      rating : 3.5,
      specification:["6.58 inches",
       " Kirin 990 5G",
        "Quad rear (50MP+12MP+40MP+TOF 3D), 32MP front",
        "4200mAh",
        "Leica Quad Camera System",
        "Dual-View Video",
       " Water and dust resistant"]
    },
    {
      id: 9,
      name: 'Motorola Edge+ (Thunder Grey, 256GB ) ',
      brand: 'Motorola',
      price: 53000,
      image: 'https://img.gkbcdn.com/s3/p/2020-12-30/Xiaomi-Mi-11-5G-Smartphone-6-81-Inch-8GB-256GB-Blue-427114-0.jpg',
      isAvailable: true,
      rating : 4.5,
      specification: ["6.7 inches",
        "Snapdragon 865",
        "Triple rear (108MP+16MP+8MP), 25MP front",
        "5000mAh",
        "5G connectivity",
        "Edge display",
        "Ready For platform"]
    },
    {
      id: 10,
      name: 'Realme GT Neo 2   (Neo Green, 128GB ',
      brand: 'Realme',
      price: 29000,
      image: '',
      isAvailable: true,
      rating : 4.5,
      specification: ["6.62 inches",
        "Snapdragon 870",
        "Triple rear (64MP+8MP+2MP), 16MP front",
        "5000mAh",
        "120Hz Super AMOLED display",
        "Dual stereo speakers",
        "Dolby Atmos"]
    }
  
  ];
